In [1]:
import sys
!conda install --yes --prefix {sys.prefix} numpy

# ! ejecuta un comando del sistema desde el notebook, el comando ejecutado fue:
print("Comando ejecutado:conda install --yes --prefix {"+sys.prefix+"} numpy")

Solving environment: ...working... done

## Package Plan ##

  environment location: D:\ProgramasC\Anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.3                |           py37_0         2.8 MB
    ------------------------------------------------------------
                                           Total:         2.8 MB

The following packages will be UPDATED:

  conda                                       4.7.12-py37_0 --> 4.8.3-py37_0




conda-4.8.3          | 2.8 MB    |            |   0% 
conda-4.8.3          | 2.8 MB    |            |   1% 
conda-4.8.3          | 2.8 MB    | ##6        |  27% 
conda-4.8.3          | 2.8 MB    | #####1     |  51% 
conda-4.8.3          | 2.8 MB    | #######    |  70% 
conda-4.8.3          | 2.8 MB    | ########6  |  87% 
conda-4.8.3          | 2.8 MB    | ########## | 100% 
Preparing t

In [2]:
import numpy as np

# Ejercicio 1

En data science y programación científica es común necesitar vectores con valores dentro de cierto intervalo, pero con sub-intervalos internos con diference espaciamiento ,por ejemplo:

[0. , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1. ]

El primer sub-intervalo incrementa de 0.1 en 0.1 , el segundo de 0.01 en 0.01 , y el tercero de 0.1 en 0.1 nuevamente.

Usando unicamente NumPy crea un vector de este tipo con el nombre xs .

nota: no es permitido usar ciclos, debe realizarse con operaciones "vectorizadas" de numpy

In [3]:
np.hstack(
(np.arange(0,0.6,0.1), 
np.arange(0.51, 0.6, 0.01), 
np.arange(0.6, 1.01, 0.1)))

array([0.  , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1.  ])

# Ejercicio 2 

En este caso usamos un ciclo para ejemplificar pero ya hemos mencionado que debemos evitarlos siempre que sea posible y usar operaciones "vectorizadas" ya que es mucho mas rápido al utilizar código pre-compilado de C, en este ejercicio debemos remplazar el calculo de xs para hacerlo de manera "vectorizada" y eliminar el ciclo for.

tip: usar slicing

In [4]:
# tu codigo aqui (~ 5 lineas de codigo):
ruido = 0.1*np.random.randn(15) #el ruido comunmente se debe a aleatoriedad o captura no exacta de info.
x = np.linspace(0,2*np.pi,15) + ruido
x = np.sin(x)

xs =  x.copy()
# codigo nuevo 
xl = np.hstack((x[1:len(x)], np.nan))
xr = np.hstack((np.nan, x[:len(x)-1]))
xs = (x + xr + xl) / 3
xs[0] = x[0]
xs[len(xs)-1] = x[len(x)-1]

    
print(x)
print(xs)

[ 0.27884291  0.26632397  0.68404632  0.9572121   0.98548323  0.76274945
  0.47325184  0.05657613 -0.58685362 -0.7873154  -0.98717057 -0.96119954
 -0.7702387  -0.45584571  0.12054513]
[ 0.27884291  0.40973773  0.6358608   0.87558055  0.90181493  0.74049484
  0.43085914 -0.01900855 -0.43919763 -0.78711319 -0.91189517 -0.90620294
 -0.72909465 -0.36851309  0.12054513]


# Ejercicio 3

Para calcular la información de una distribución de probabilidad necesitamos calcular el producto entre la información de cada posible x y su probabilidad , cada uno de estos elementos nos indica cuanta incerteza aporta cada x a la entropía de la distribución. Crea una función que calcule esto, debe recibir un vector representando a la dist. de probabilidad y devoler otro vector con el termino de entropía para cada x. Por ejemplo:

calcular_entropia([0.25,0.75])

Debe resultar en :

[0.5 , 0.31127812]

Nota: la entropía es la suma sobre estos valores, en este caso no calculamos la entropía,unicamente los termimos de su sumatoria. La entropía es:

𝑆=−∑𝑖𝑛𝑃(𝑥𝑖)𝑙𝑜𝑔2𝑃(𝑥𝑖)

In [5]:
# tu codigo aqui (~ 4 lineas de codigo)  

def entropia(n):
    return -1*(n*np.log2(n))

entropia([0.25,0.75])


array([0.5       , 0.31127812])

# Ejercicio 4

Se ha determinado también que hay costos asociados a la comunicación y relación con los clientes(llamadas,mensajes electrónicos,etc) y que estos también tienen alta correlación con el monto que estos gastan en su primer més siguiendo el modelo:
𝑐(𝑥)=(𝑥2+𝑥+𝑙𝑜𝑔(0.0001𝑥)−0.54𝑥⎯⎯⎯⎯⎯⎯⎯⎯⎯√)/100
 
Cree una función para calcular este modelo sobre valores de de gasto de nuevos clientes , y luego cree una función ganancia_neta(x,g,c) donde:

x = vector conteniendo los valores de gasto del primer mes para nuevos clientes.
g = función que estima la ganancia en función de x
c = función que estima el costo en función de x
La función realiza el calculo simple g(x) - c(x) , ya que es posible que los modelos cambien en el tiempo es común recibir como parámetro el modelo o modelos hijos de un modelo mas grande , en este caso eso se logra recibiendo como parámetro las funciones de ganancia y costo.

In [6]:
# Codigo del ejemplo anterior
def g(x):
    ganancia = (np.power(x,3) + 2.0*(np.power(x,2.0))+np.exp(0.0001*x) - np.sqrt(2.0*x))/50
    
    return ganancia
    
gastos = np.array([100,50,25])
ganancia = g(gastos)

print("Ganancias",ganancia)
# Fin del codigo del ejemplo anterior 

def c(x):
    return (x**2+x+np.log10(0.0001*x))-np.sqrt(0.54*x)/100
def gan_netadex(x,g,c):
    return g(x)-c(x)

ganancia = gan_netadex(gastos,g,c)

ganancia

Ganancias [20399.73735829  2599.82010025   337.37862871]


array([10301.81084298,    52.17309177,  -309.98256896])

# Ejercicio 5

Usando argmax crear una función mode(x) para calcular la moda de un vector x , esta función debe devolver una tupla de 2 elementos de la forma:

(valor,conteo)

tip investigar y auxiliarse de otras funciones de numpy y np.argmax, no olvidar trabajar todo vectorizado, sin ciclos.

In [19]:
def mode(x):
    ## tu codigo aqui (~ 3 lineas de codigo):
    counts = np.bincount(x)
    return np.argmax(counts)
   

a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
print(mode(a))

1


# Ejercicio 6

Crear una función para calcular la entropía de una distribución de probabilidad representada como un vector.
𝑆=−∑𝑖𝑛𝑃(𝑥𝑖)𝑙𝑜𝑔2𝑃(𝑥𝑖)
 
Nota: a diferencia del ejercicio anterior donde solo calculamos los términos de la entropía, en este caso si calculamos el valor completo de la entropía, que como mencionamos es una medida de incerteza en una distribución de probabilidad.

recordatorio: no usar ciclos solo operaciones vectorizadas.

In [7]:
# tu codigo aqui (~ 3 lineas de codigo)
def entropia(n):
    return -np.sum(n*np.log2(n)) 

entropia([0.25,0.75])

0.8112781244591328

# Ejercicio 7

En ML usamos la entropía cruzada como una forma de medir que tan bueno es un modelo de variables discretas a través de comparar la distribución de probabilidad que el modelo produce o predice, vs la distribución de probabilidad real dada por los datos de entrenamiento.

Podemos ver el siguiente ejemplo que define la forma en que se calcula la entropía cruzada y nos muestra un caso específico:


En este caso interpretamos así: El problema consiste en un modelo o algoritmo de ML que debe producir un vector de 3 elementos indicando la probabilidad de que ciertos datos X pertenezcan a una de 3 categorías.

El modelo de ML produce un vector que indica que estima un 70% de probabilidad de que se trate de la categoría 0, 20% de probabilidad de que se trate de la categoría 1 y 10% de que se trate de la categoría 2.
Los datos reales nos dicen que se trataba de un caso donde con total certeza se sabe que se trata de la categoría 0
La entropía cruzada(a calcular en el ejercicio) nos indica que tan buena es la estimación del modelo, una EC de 0 es un modelo perfecto(en este caso un modelo que predice 100% de prob para la clase 0)
Nota

Aun que para calcular la entropía usamos logaritmos en base 2, en ML para calcular la entropía cruzada se usa logaritmo natural ya que con este se cumple el proposito estimar que tanto se alejan las predicciones del modelo de ML de los datos reales y es comunmente mas rápido de calcular en la computadora.

Ya que estamos trabajando con vectores que representan distribuciones de probabilidad , podemos toparnos con lo que se conoce como : sparse vectors(vectores donde la mayoría de elementos son 0), esto puede producir problemas ya que le logaritmo de 0 no esta definido, tu solución debe tomar en cuenta esto y evitar que devuelva "nan"

In [8]:
def cross_entropy(Y,Y_hat):
    ##tu codigo aqui (~ 1 lineas de codigo)
    return np.sum(-((Y*np.log(Y_hat))+((1-Y)*np.log(1- Y_hat))))
    

y  = np.array([1.0,0,0])
y_hat = np.array([0.7,0.2,0.1])

cross_entropy(y,y_hat)

0.6851790109107685

# Ejercicio 8

Crear una función que reciba como parámetro un vector x y calcule su magnitud o norma(euclidiana o L2) ,luego usarla para evaluar 2 vectores que representan los errores generados por 2 modelos de machine learning y concluir cual de los 2 modelos es mejor.

In [9]:
def magnitud(x):
    ## tu codigo aqui (~ 1 linea de codigo)
    return np.sqrt(np.inner(x,x))

errores_modelo1 = np.array([1,2,1,2])
errores_modelo2 = np.array([0,1,1,2])

print(magnitud(errores_modelo1))
print(magnitud(errores_modelo2))

3.1622776601683795
2.449489742783178


# Ejercicio 9

Usando la función del ejercicio anterior, crea otra función normalizar(x) que reciba de parámetro un vector x aplique normalización sobre este, el resultado debe ser un nuevo vector del tamaño de x cuya magnitud es igual a 1.0

In [10]:
def normalizar(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    return x/magnitud(x)
    

print(magnitud(normalizar(errores_modelo1)))
print(normalizar(errores_modelo2))

1.0
[0.         0.40824829 0.40824829 0.81649658]


# Ejercicio 10

la correlación cruzada es una medida de similitud entre 2 funciones como resultado de "desplazar" una sobre la otra, comunmente es usada para encontrar características relevantes en una función desconocida o no controlada.

En procesamiento de señales por ejemplo es usada para buscar y/o filtrar en una señal que varia en el tiempo cierta caracaterística de interés. Aveces es llamada también "sliding dot product" consiste en aplicar en cada punto de una función F el producto punto con cierta función G(comunmente mas corta) y luego "deslizar" G a un nuevo punto de la función, el resultado es una nueva función H que se interpreta como :cuanto se parece en cada punto la función F a la característica G.


En este ejercicio usamos correlación cruzada para calcular las medias moviles promediando 3 puntos que ya vimos en otro ejemplo:

El primer paso es definir la función G que define el "filtro" a aplicar, para este caso consiste simplemente en un vector con 3 elementos donde cada elemento corresponde a 1/3, luego debemos aplicar el producto punto sobre cada punto de la función o datos originales(en este ejemplo llamados x) a traves aplicar el producto punto en cada elemento "corriendolo" de uno en uno

In [11]:
ruido = 0.1*np.random.randn(15) #el ruido comunmente se debe a aleatoriedad o captura no exacta de info.
x = np.linspace(0,2*np.pi,15) + ruido
x = np.sin(x)

filtro = np.array([1/3,1/3,1/3])

## tu codigo aqui (~ 3 linea de codigo)
xs = x.copy()
for i in range(1,len(x)-1):
    xs[i] = np.inner(xs[i-1:i+2], filtro)
    
xs

array([-0.13611255,  0.38709979,  0.72832335,  0.88217361,  0.87991002,
        0.73579385,  0.45331896,  0.04253379, -0.42234175, -0.75482524,
       -0.90759577, -0.88477967, -0.74080398, -0.46650864, -0.09254761])

# Ejercicio 11

dado el vector x, usar operadores lógicos sobre vectores y acceso a elementos usando vectores booleanos , escribir un programa que calcule eun nuevo vector z conteniendo el valor absoluto de el vector x.

nota No se puede usar np.abs() ni ciclos

tip usar un vector booleano para saber que elementos son negativos y deben ser multiplicados por -1

In [12]:
x = np.linspace(-2,2,9)


## tu codigo aqui (~ 4 linea de codigo)
def mipropioabs(x):
    v = x.copy()
    v[v<0] = -v[v<0]
    return v

mipropioabs(x)

array([2. , 1.5, 1. , 0.5, 0. , 0.5, 1. , 1.5, 2. ])

# Ejercicio 12

Implementar la función:

 
Esta debe funcionar para vectores de cualquier tamaño x:

def h(x):

...
nota debe ser implementada sin ciclos o ifs

In [13]:
def h(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    a = [x < 0, (x >= 0) * (x <= 1), x > 1]
    b = [0,1,0]
    c = np.select(a,b)
    ##
    return c

x = np.array([0.1,-2,0.5,5])
print(h(x))

[1 0 1 0]


# Ejercicio 13

Usando select implementar una función k(x) con la siguiente definición:

Select y performance
Aun que select es muy conveniente y útil , no es la opción mas eficiente esto debido a que evalua todas las condiciones y todos los resultados, en programación en general buscamos escribir los programas de la manera mas eficiente posible y evitar calculos innecesarios, esto se vuelve vital en ciencia de datos cuando procesamos grandes volúmenes de información, por eso NumPy nos provee la alternativa a select llamada piecewise que funciona de manera similar .

Este funciona similar a select pero en vez de calcular todos los posibles resultados, calcula solo aquellos para los que la condición es True e ignora los False,sintácticamente piecewise requiere que los "resultados" sesan calcuados usando una lista de funciones por lo cual todos los resultados deben estar contenidos en una función y el objeto función ser enviado a piecewise (si la función solo se utiliza una vez para este propósito, se puede usar funciones anónimas o lambda).

In [14]:
x = np.linspace(1,10,10)
condiciones = [x<0,(0<=x)*(x<1),(1<=x)*(x<2), x>=2]
resultados = [-x,x**3,x**2,4]
k = np.select(condiciones,resultados,1)

print(x)
print(k)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


# Ejercicio 14

Investigar piecewise y:

Usarlo para implementar la función anterior de manera eficiente
Usar piscewise para implementar la función:

 
Nuevamente, sin utilizar ciclos ni ifs

In [15]:
def m(x):
    return np.piecewise(x, [x < 0, (x >= 0)*(x < 1), x >=1], [lambda x: np.exp(2*x), 1, lambda x: np.exp(1-x)])

x =np.arange(-1,0.52,30.45)
m(x)

array([0.13533528])

# Investigar

-Proyección vectorial

-Definir una función para calculo en numpy

-interpretación

-aplicación o caso de uso en DS u otras ciencias de tu interés: solo se necesita nombrar el caso de uso, no desarrollarlo o programarlo, tip: Hay un algoritmo de ML cuyo nombre puede ser útil.

-Producto cruz

-calculo en numpy

-interpretación

-aplicación o caso de uso en DS u otras ciencias de tu interés: solo se necesita nombrar el caso de uso, no desarrollarlo o programarlo

#### Proyección vectorial

Es la sombra que proyecta el ventor sobre alguno de los ejes o sobre otro vector.

Vamos a representar gráficamente la proyección del vector u sobre el vector v (que como veremos más adelante, no es igual a la proyección del vector v sobre u). Para ello, desde el extremo de u, trazamos una recta perpendicular al vector v:

<img loading="lazy" class="aligncenter size-full wp-image-18337 lazyloaded" src="https://ekuatio.com/wp-content/uploads/proyeccion-vectores-2.png" alt="" data-lazy-srcset="https://ekuatio.com/wp-content/uploads/proyeccion-vectores-2.png 239w, https://ekuatio.com/wp-content/uploads/proyeccion-vectores-2-100x59.png 100w" data-lazy-sizes="(max-width: 239px) 100vw, 239px" data-lazy-src="https://ekuatio.com/wp-content/uploads/proyeccion-vectores-2.png" sizes="(max-width: 239px) 100vw, 239px" srcset="https://ekuatio.com/wp-content/uploads/proyeccion-vectores-2.png 239w, https://ekuatio.com/wp-content/uploads/proyeccion-vectores-2-100x59.png 100w" data-was-processed="true" width="239" height="141">

#### Aplicación o caso de uso en DS

Árboles de decisión: Un árbol de decisiones es una herramienta de apoyo a la decisión que utiliza un gráfico o un modelo similar a un árbol de decisiones y sus posibles consecuencias, incluidos los resultados de eventos fortuitos, los costos de recursos y la utilidad. Presentan una apariencia como esta:

<img class="size-full wp-image-570 aligncenter" src="https://www.raona.com/wp-content/uploads/2017/05/arbol_decision.png" alt="" srcset="/wp-content/uploads/2017/05/arbol_decision.png 561w, /wp-content/uploads/2017/05/arbol_decision-300x150.png 300w" sizes="(max-width: 561px) 100vw, 561px" width="561" height="280">

#### Interpretación

In [18]:
# importamos las librerías que necesitamos
from sklearn.datasets import load_iris # datos de iris
from sklearn.tree import DecisionTreeClassifier # árbol de decisión para clasificación

iris = load_iris()
print(iris.DESCR) # información sobre del conjunto de datos iris

# lo más relevante es:
#    :Number of Instances: 150 (50 in each of three classes)
#    :Number of Attributes: 4 numeric, predictive attributes and the class
#    :Attribute Information:
#        - sepal length in cm
#        - sepal width in cm
#        - petal length in cm
#        - petal width in cm
#        - class:
#                - Iris-Setosa
#                - Iris-Versicolour
#                - Iris-Virginica

# veamos 4 filas donde ocurre un cambio de clase
print(iris.data[48:52,:])

# da el resultado
# [[5.3 3.7 1.5 0.2]
#  [5.  3.3 1.4 0.2]
#  [7.  3.2 4.7 1.4]
#  [6.4 3.2 4.5 1.5]]

# para la variable a predecir también hacemos lo mismo
print(iris.target[48:52])

# La clase 0 es Iris-Setosa, la 1 es Iris-Versicolor y la 2 es Iris-Virginica
# [0 0 1 1]

# Vamos a crear y entrenar un árbol de decisión para clasificar los datos de Iris
tree = DecisionTreeClassifier(max_depth=2, random_state=42) # vamos a usar un árbol de profundidad 2
tree.fit(iris.data, iris.target) # entrenamiento del árbol

# podemos usar el método predict para obtener predicciones
print( tree.predict(iris.data[47:53]) )

# resulta en
# [0 0 0 1 1 1]

# si queremos saber las probabilidades podemos usar el método predict_proba
print( tree.predict_proba(iris.data[47:53]) )

# la primera clase (Setosa) es la primera columna, la segunda clase en la segunda, etc..
# este es el resultado:
# [[1.         0.         0.        ]
#  [1.         0.         0.        ]
#  [1.         0.         0.        ]
#  [0.         0.90740741 0.09259259]
#  [0.         0.90740741 0.09259259]
#  [0.         0.90740741 0.09259259]]

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

#### Producto Cruz

Es otro vector cuya dirección es perpendicular a los dos vectores y su sentido sería igual al avance de un sacacorchos al girar de u a v. Su módulo es igual a:

<img src="https://www.superprof.es/apuntes/wp-content/uploads/2019/07/producto-cruz-2.gif">